#cloud-config
package_update: true
package_upgrade: true

packages:
  - htop
  - iotop
  - sysstat
  - curl
  - wget
  - python3

write_files:
  - path: /etc/sysctl.d/99-high-performance.conf
    content: |
      # Network optimizations for high load
      # net.core.somaxconn = 65535
      # net.core.netdev_max_backlog = 5000
      # net.core.rmem_max = 134217728
      # net.core.wmem_max = 134217728
      # net.ipv4.tcp_rmem = 4096 65536 134217728
      # net.ipv4.tcp_wmem = 4096 65536 134217728
      # net.ipv4.tcp_congestion_control = bbr
      # net.ipv4.tcp_slow_start_after_idle = 0
      # net.ipv4.tcp_tw_reuse = 1
      # net.ipv4.ip_local_port_range = 1024 65535
      # net.ipv4.tcp_max_syn_backlog = 65535
      # net.ipv4.tcp_max_tw_buckets = 1440000
      # net.ipv4.tcp_fin_timeout = 15
      # net.ipv4.tcp_keepalive_time = 300
      # net.ipv4.tcp_keepalive_probes = 5
      # net.ipv4.tcp_keepalive_intvl = 15
      
      # File system optimizations
      fs.file-max = 2097152
      fs.nr_open = 1048576
      
      # Virtual memory optimizations
      vm.swappiness = 10
      vm.dirty_ratio = 15
      vm.dirty_background_ratio = 5
      
      # Enable IP forwarding for gateway functionality
      net.ipv4.ip_forward = 1

  - path: /etc/security/limits.d/99-performance.conf
    content: |
      * soft nofile 1048576
      * hard nofile 1048576

runcmd:
  - sysctl -p /etc/sysctl.d/99-high-performance.conf
  - echo "System performance tuning applied"