#cloud-config
package_update: true
package_upgrade: true

packages:
  - htop
  - iotop
  - sysstat
  - curl
  - wget
  - python3

write_files:
  - path: /etc/sysctl.d/99-high-performance.conf
    content: |
      net.ipv4.ip_local_port_range = 1024 65535
      fs.file-max = 2097152
      fs.nr_open = 1048576
      
      # Virtual memory optimizations
      vm.swappiness = 10
      vm.dirty_ratio = 15
      vm.dirty_background_ratio = 5

  - path: /etc/security/limits.d/99-performance.conf
    content: |
      * soft nofile 1048576
      * hard nofile 1048576

runcmd:
  - sysctl -p /etc/sysctl.d/99-high-performance.conf
  - echo "System performance tuning applied"