---
- name: Create API server group
  group:
    name: "{{ api_server_group }}"
    system: yes

- name: Create API server user
  user:
    name: "{{ api_server_user }}"
    group: "{{ api_server_group }}"
    system: yes
    shell: /bin/false
    home: "{{ api_server_home }}"
    create_home: yes

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ api_server_user }}"
    group: "{{ api_server_group }}"
    mode: '0755'
  loop:
    - "{{ api_server_home }}"
    - "{{ api_server_config_dir }}"
    - "/var/log/bulbul"

- name: Copy API server binary
  copy:
    src: "files/api-server"
    dest: "{{ api_server_binary_path }}"
    owner: "{{ api_server_user }}"
    group: "{{ api_server_group }}"
    mode: '0755'
    force: true
  notify: restart api-server

- name: Copy sync seats binary
  copy:
    src: "files/sync-seats"
    dest: "{{ sync_seats_binary_path }}"
    owner: "{{ api_server_user }}"
    group: "{{ api_server_group }}"
    mode: '0755'
    force: true

- name: Copy sync seats script
  template:
    src: "sync-seats.sh.j2"
    dest: "{{ api_server_home }}/sync-seats.sh"
    owner: "{{ api_server_user }}"
    group: "{{ api_server_group }}"
    mode: '0755'

- name: Create environment file
  template:
    src: api-server.env.j2
    dest: "{{ api_server_config_dir }}/api-server.env"
    owner: "{{ api_server_user }}"
    group: "{{ api_server_group }}"
    mode: '0640'
  notify: restart api-server

- name: Create systemd service file
  template:
    src: api-server.service.j2
    dest: "/etc/systemd/system/{{ api_server_service_name }}.service"
    mode: '0644'
  notify:
    - reload systemd
    - restart api-server

- name: Create log rotation configuration
  copy:
    content: |
      {{ log_file }} {
          daily
          missingok
          rotate 7
          compress
          delaycompress
          notifempty
          create 0644 {{ api_server_user }} {{ api_server_group }}
          postrotate
              systemctl reload {{ api_server_service_name }} || true
          endscript
      }
    dest: "/etc/logrotate.d/{{ api_server_service_name }}"
    mode: '0644'

- name: Start and enable API server service
  systemd:
    name: "{{ api_server_service_name }}"
    state: started
    enabled: yes
    daemon_reload: yes


