version: '3.8'

services:
  bulbul-api:
    build: .
    ports:
      - "8081:8081"
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/api/events"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
