---

- name: Install Valkey and PostgreSQL client
  apt:
    name:
      - valkey
      - postgresql-client
      - python3-psycopg2
      - python3-redis
    state: present
    update_cache: yes

- name: Create Valkey directories
  file:
    path: "{{ item }}"
    state: directory
    owner: valkey
    group: valkey
    mode: '0755'
  loop:
    - /etc/valkey
    - /var/lib/valkey
    - /var/log/valkey

- name: Configure Valkey
  template:
    src: valkey.conf.j2
    dest: /etc/valkey/valkey.conf
    owner: valkey
    group: valkey
    mode: '0640'
    backup: yes
  notify: restart valkey

- name: Start and enable Valkey
  systemd:
    name: valkey
    state: started
    enabled: yes
    daemon_reload: yes

- name: Deploy user loading script
  template:
    src: load_users_to_valkey.py
    dest: /usr/local/bin/load_users_to_valkey.py
    mode: '0755'
    owner: root
    group: root

- name: Load users to Valkey
  command: python3 /usr/local/bin/load_users_to_valkey.py
  environment:
    DB_HOST: "{{ postgres_host }}"
    DB_PORT: "{{ postgres_port }}"
    DB_NAME: "{{ postgres_database }}"
    DB_USER: "{{ postgres_user }}"
    DB_PASSWORD: "{{ postgres_password }}"
    VALKEY_HOST: "{{ valkey_bind }}"
    VALKEY_PORT: "{{ valkey_port }}"
    VALKEY_PASSWORD: "{{ valkey_requirepass }}"
    VALKEY_USERS_HASH_KEY: "users:auth"
  register: load_users_result
  failed_when: load_users_result.rc != 0

- name: Display user loading result
  debug:
    var: load_users_result.stdout_lines