---
- name: Provision node exporters
  hosts: all
  become: yes
  gather_facts: yes
  
  roles:
    - node_exporter
  tags: monitoring

- name: Provision monitoring
  hosts: monitoring
  become: yes
  gather_facts: yes
  
  roles:
    - monitoring
  tags: monitoring


- name: Provision Load Balancer
  hosts: load_balancer
  become: yes
  gather_facts: yes
  
  roles:
    - load_balancer
  tags: load_balancer

- name: Provision postgresql
  hosts: postgres
  become: yes
  gather_facts: yes
  
  roles:
    - postgresql
  tags: postgresql

- name: Provision valkey
  hosts: valkey
  become: yes
  gather_facts: yes
  
  roles:
    - valkey
  tags: valkey

- name: Deploy API Server
  hosts: api_servers
  become: yes
  gather_facts: yes
  
  roles:
    - api_server
  tags: api_server