---
- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted
    daemon_reload: yes

- name: restart grafana
  systemd:
    name: grafana-server
    state: restarted
    daemon_reload: yes

- name: reload prometheus
  systemd:
    name: prometheus
    state: reloaded

- name: reload grafana
  systemd:
    name: grafana-server
    state: reloaded