---
- name: restart elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
    daemon_reload: yes
  become: yes

- name: reload elasticsearch
  systemd:
    name: elasticsearch
    state: reloaded
    daemon_reload: yes
  become: yes

- name: start elasticsearch
  systemd:
    name: elasticsearch
    state: started
    enabled: yes
  become: yes

- name: stop elasticsearch
  systemd:
    name: elasticsearch
    state: stopped
  become: yes