---
# PostgreSQL version
postgresql_version: "16"

# Database configuration
postgresql_database: "bulbul"

# Connection settings
postgresql_port: 5432
postgresql_listen_addresses: "0.0.0.0"
postgresql_max_connections: 2000

# Memory settings (adjust based on available RAM)
postgresql_shared_buffers: "256MB"
postgresql_effective_cache_size: "1GB"
postgresql_work_mem: "4MB"
postgresql_maintenance_work_mem: "64MB"

# WAL settings
postgresql_wal_buffers: "16MB"
postgresql_checkpoint_completion_target: 0.9
postgresql_max_wal_size: "1GB"
postgresql_min_wal_size: "80MB"

# Query planner
postgresql_random_page_cost: 1.1
postgresql_effective_io_concurrency: 200

# Logging
postgresql_log_destination: "stderr"
postgresql_logging_collector: "on"
postgresql_log_directory: "log"
postgresql_log_filename: "postgresql-%Y-%m-%d_%H%M%S.log"
postgresql_log_min_duration_statement: 1000

# Performance monitoring
postgresql_track_activities: "on"
postgresql_track_counts: "on"
postgresql_track_io_timing: "on"
postgresql_track_functions: "all"

# Security
postgresql_ssl: "off"  # Enable if needed
postgresql_authentication_timeout: "1min"

# Postgres superuser configuration (for API server access)
postgresql_postgres_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38633233643332343565363633626566353532343764616436353364346633666366646232663665
          6663663134643935623036386239643666393530313965610a363331663338343631363465653439
          62393265376135353832343664623634356438666632663962613933306564643366313233366666
          3232346566303866340a343061643636373338303434373865643665346532336230386333316164
          65643838613066373065353237343936363862306332343837373363306430663236

# Data loading configuration
postgresql_load_data: false
postgresql_data_dir: "/tmp/postgresql_data"

# Data source URLs
postgresql_data_sources:
  users_sql: "https://github.com/hackload-kz/data/releases/download/2025-08-15/users.sql"
  events_sql: "https://github.com/hackload-kz/data/releases/download/2025-08-15/events.sql"
  events_archive_zip: "https://github.com/hackload-kz/data/releases/download/2025-08-15/events_archive.sql.zip"