---
- name: restart postgresql
  systemd:
    name: postgresql
    state: restarted

- name: reload postgresql
  systemd:
    name: postgresql
    state: reloaded

- name: start postgresql
  systemd:
    name: postgresql
    state: started